name: Docs
on: [push]
permissions:
  contents: write
jobs:
  docs:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "Building docs"
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          clean-exclude: docs
